project_id = "qqgtvhtaoxrdnxarnvcw"

[functions.notify-plumbers]
verify_jwt = false

[functions.assign-request]
verify_jwt = false

[functions.check-expired-assignments]
verify_jwt = false

[functions.accept-request]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-client-confirmation]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.notify-owner-subscription]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = false

[functions.create-test-request]
verify_jwt = false

[functions.notify-owner]
verify_jwt = false
