project_id = "qqgtvhtaoxrdnxarnvcw"

[functions.notify-plumbers]
verify_jwt = false

[functions.assign-request]
verify_jwt = false

[functions.check-expired-assignments]
verify_jwt = false

[functions.accept-request]
verify_jwt = false
