CREATE TABLE public.assignment_config (id uuid DEFAULT gen_random_uuid() NOT NULL, urgency text NOT NULL, plan_type text NOT NULL, timer_minutes integer NOT NULL, max_attempts integer DEFAULT 3, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE public.assignment_logs (id uuid DEFAULT gen_random_uuid() NOT NULL, request_id uuid NOT NULL, plumber_id uuid NOT NULL, plumber_plan text NOT NULL, assigned_at timestamptz DEFAULT now() NOT NULL, expires_at timestamptz NOT NULL, responded boolean DEFAULT false, response_type text, response_at timestamptz, created_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE public.contact_logs (id uuid DEFAULT gen_random_uuid() NOT NULL, plumber_id uuid NOT NULL, request_id uuid NOT NULL, contacted_at timestamptz DEFAULT now());
CREATE TABLE public.contact_unlocks (id uuid DEFAULT gen_random_uuid() NOT NULL, plumber_id uuid NOT NULL, request_id uuid NOT NULL, is_exclusive boolean DEFAULT false NOT NULL, unlocked_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE public.conversation_messages (id uuid DEFAULT gen_random_uuid() NOT NULL, conversation_id uuid NOT NULL, sender_type text NOT NULL, content text NOT NULL, read_by_recipient boolean DEFAULT false NOT NULL, created_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT conversation_messages_content_check CHECK (length(content) >= 1 AND length(content) <= 4000),
  CONSTRAINT conversation_messages_sender_type_check CHECK (sender_type = ANY (ARRAY['plumber'::text, 'client'::text])));
CREATE TABLE public.conversations (id uuid DEFAULT gen_random_uuid() NOT NULL, request_id uuid NOT NULL, plumber_id uuid NOT NULL, client_access_token text DEFAULT encode(extensions.gen_random_bytes(32), 'hex') NOT NULL, quote_amount_cents integer, last_message_at timestamptz DEFAULT now() NOT NULL, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE public.credit_packages (id uuid DEFAULT gen_random_uuid() NOT NULL, name text NOT NULL, credits integer NOT NULL, price_cents integer NOT NULL, price_per_credit numeric(10,2) NOT NULL, stripe_price_id text, is_active boolean DEFAULT true NOT NULL, sort_order integer DEFAULT 0 NOT NULL, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, amount_cents integer DEFAULT 0 NOT NULL);
CREATE TABLE public.credit_transactions (id uuid DEFAULT gen_random_uuid() NOT NULL, plumber_id uuid NOT NULL, transaction_type text NOT NULL, credits integer NOT NULL, balance_after integer NOT NULL, package_id uuid, stripe_payment_intent_id text, amount_cents integer, request_id uuid, unlock_reason text, description text, created_at timestamptz DEFAULT now() NOT NULL, amount_cents_delta integer DEFAULT 0 NOT NULL, balance_after_cents integer DEFAULT 0 NOT NULL,
  CONSTRAINT credit_transactions_transaction_type_check CHECK (transaction_type = ANY (ARRAY['purchase'::text, 'unlock'::text, 'refund'::text, 'bonus'::text])));
CREATE TABLE public.intervention_pricing (intervention_type public.intervention_type NOT NULL, tier text NOT NULL, multiplier numeric DEFAULT 1.0 NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE public.italian_cities (id uuid DEFAULT gen_random_uuid() NOT NULL, name text NOT NULL, province_code text NOT NULL, province_name text NOT NULL, region text NOT NULL, cap text[] DEFAULT '{}'::text[] NOT NULL, created_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE public.plumber_credits (id uuid DEFAULT gen_random_uuid() NOT NULL, plumber_id uuid NOT NULL, balance integer DEFAULT 0 NOT NULL, total_purchased integer DEFAULT 0 NOT NULL, total_spent integer DEFAULT 0 NOT NULL, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, balance_cents integer DEFAULT 0 NOT NULL, total_purchased_cents integer DEFAULT 0 NOT NULL, total_spent_cents integer DEFAULT 0 NOT NULL);
CREATE TABLE public.plumber_profiles (id uuid DEFAULT gen_random_uuid() NOT NULL, user_id uuid NOT NULL, full_name text NOT NULL, business_name text NOT NULL, email text NOT NULL, phone text NOT NULL, main_city text NOT NULL, description text, intervention_types public.intervention_type[] DEFAULT '{}'::public.intervention_type[], availability public.availability_type[] DEFAULT '{}'::public.availability_type[], service_areas text[] DEFAULT '{}'::text[], email_verified boolean DEFAULT false, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now(), photo_url text, rating numeric(2,1) DEFAULT 0, review_count integer DEFAULT 0);
CREATE TABLE public.plumber_subscriptions (id uuid DEFAULT gen_random_uuid() NOT NULL, plumber_id uuid NOT NULL, plan_type public.subscription_plan NOT NULL, status public.subscription_status DEFAULT 'pending'::public.subscription_status NOT NULL, current_period_start timestamptz, current_period_end timestamptz, exclusive_contacts_used integer DEFAULT 0 NOT NULL, stripe_customer_id text, stripe_subscription_id text, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, trial_ends_at timestamptz, monthly_contact_limit integer, monthly_contacts_used integer DEFAULT 0, contacts_reset_at timestamptz DEFAULT now(), is_available boolean DEFAULT true, last_assigned_at timestamptz, free_requests_remaining integer DEFAULT 3, is_trial boolean DEFAULT true);
CREATE TABLE public.service_requests (id uuid DEFAULT gen_random_uuid() NOT NULL, intervention_type public.intervention_type NOT NULL, city text NOT NULL, description text NOT NULL, urgency public.urgency_type NOT NULL, property_type public.property_type NOT NULL, accessibility public.accessibility_type NOT NULL, client_name text NOT NULL, client_phone text NOT NULL, client_email text, privacy_accepted boolean DEFAULT false NOT NULL, status text DEFAULT 'new'::text, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now(), assigned_plumber_id uuid, is_exclusive boolean DEFAULT false NOT NULL, assigned_at timestamptz, assignment_started_at timestamptz, assignment_expires_at timestamptz, assignment_round integer DEFAULT 0, accepted_at timestamptz, accepted_by_id uuid, current_assignee_plan text, wizard_answers jsonb, client_user_id uuid, phone_contact_allowed boolean DEFAULT true NOT NULL);
CREATE TABLE public.service_requests_public_meta (request_id uuid NOT NULL, city text NOT NULL, intervention_type public.intervention_type NOT NULL, urgency public.urgency_type NOT NULL, property_type public.property_type NOT NULL, accessibility public.accessibility_type NOT NULL, status text DEFAULT 'new'::text NOT NULL, is_exclusive boolean DEFAULT false NOT NULL, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE public.subscription_plans (id uuid DEFAULT gen_random_uuid() NOT NULL, plan_type public.subscription_plan NOT NULL, name text NOT NULL, description text, price_monthly numeric(10,2) NOT NULL, max_exclusive_contacts integer, contacts_are_exclusive boolean DEFAULT false NOT NULL, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE public.unlock_costs (id uuid DEFAULT gen_random_uuid() NOT NULL, urgency text NOT NULL, credits_cost integer NOT NULL, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, cost_cents integer DEFAULT 0 NOT NULL);
CREATE TABLE public.unregistered_plumbers (id uuid DEFAULT gen_random_uuid() NOT NULL, full_name text NOT NULL, phone text NOT NULL, city text DEFAULT 'Napoli'::text NOT NULL, is_active boolean DEFAULT true NOT NULL, notes text, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE public.whatsapp_logs (id uuid DEFAULT gen_random_uuid() NOT NULL, recipient_phone text NOT NULL, recipient_name text, message_type text DEFAULT 'assignment'::text NOT NULL, request_id uuid, plumber_id uuid, status text DEFAULT 'pending'::text NOT NULL, error_message text, respond_io_message_id text, created_at timestamptz DEFAULT now() NOT NULL, delivered_at timestamptz, read_at timestamptz);

ALTER TABLE public.assignment_config ADD CONSTRAINT assignment_config_pkey PRIMARY KEY (id);
ALTER TABLE public.assignment_config ADD CONSTRAINT assignment_config_urgency_plan_type_key UNIQUE (urgency, plan_type);
ALTER TABLE public.assignment_logs ADD CONSTRAINT assignment_logs_pkey PRIMARY KEY (id);
ALTER TABLE public.contact_logs ADD CONSTRAINT contact_logs_pkey PRIMARY KEY (id);
ALTER TABLE public.contact_logs ADD CONSTRAINT contact_logs_plumber_id_request_id_key UNIQUE (plumber_id, request_id);
ALTER TABLE public.contact_unlocks ADD CONSTRAINT contact_unlocks_pkey PRIMARY KEY (id);
ALTER TABLE public.contact_unlocks ADD CONSTRAINT contact_unlocks_plumber_id_request_id_key UNIQUE (plumber_id, request_id);
ALTER TABLE public.conversation_messages ADD CONSTRAINT conversation_messages_pkey PRIMARY KEY (id);
ALTER TABLE public.conversations ADD CONSTRAINT conversations_client_access_token_key UNIQUE (client_access_token);
ALTER TABLE public.conversations ADD CONSTRAINT conversations_pkey PRIMARY KEY (id);
ALTER TABLE public.conversations ADD CONSTRAINT conversations_request_id_plumber_id_key UNIQUE (request_id, plumber_id);
ALTER TABLE public.credit_packages ADD CONSTRAINT credit_packages_pkey PRIMARY KEY (id);
ALTER TABLE public.credit_transactions ADD CONSTRAINT credit_transactions_pkey PRIMARY KEY (id);
ALTER TABLE public.intervention_pricing ADD CONSTRAINT intervention_pricing_pkey PRIMARY KEY (intervention_type);
ALTER TABLE public.italian_cities ADD CONSTRAINT italian_cities_pkey PRIMARY KEY (id);
ALTER TABLE public.plumber_credits ADD CONSTRAINT plumber_credits_pkey PRIMARY KEY (id);
ALTER TABLE public.plumber_credits ADD CONSTRAINT plumber_credits_plumber_id_key UNIQUE (plumber_id);
ALTER TABLE public.plumber_profiles ADD CONSTRAINT plumber_profiles_pkey PRIMARY KEY (id);
ALTER TABLE public.plumber_profiles ADD CONSTRAINT plumber_profiles_user_id_key UNIQUE (user_id);
ALTER TABLE public.plumber_subscriptions ADD CONSTRAINT plumber_subscriptions_pkey PRIMARY KEY (id);
ALTER TABLE public.plumber_subscriptions ADD CONSTRAINT plumber_subscriptions_plumber_id_key UNIQUE (plumber_id);
ALTER TABLE public.service_requests ADD CONSTRAINT service_requests_pkey PRIMARY KEY (id);
ALTER TABLE public.service_requests_public_meta ADD CONSTRAINT service_requests_public_meta_pkey PRIMARY KEY (request_id);
ALTER TABLE public.subscription_plans ADD CONSTRAINT subscription_plans_pkey PRIMARY KEY (id);
ALTER TABLE public.subscription_plans ADD CONSTRAINT subscription_plans_plan_type_key UNIQUE (plan_type);
ALTER TABLE public.unlock_costs ADD CONSTRAINT unlock_costs_pkey PRIMARY KEY (id);
ALTER TABLE public.unlock_costs ADD CONSTRAINT unlock_costs_urgency_key UNIQUE (urgency);
ALTER TABLE public.unregistered_plumbers ADD CONSTRAINT unregistered_plumbers_phone_unique UNIQUE (phone);
ALTER TABLE public.unregistered_plumbers ADD CONSTRAINT unregistered_plumbers_pkey PRIMARY KEY (id);
ALTER TABLE public.whatsapp_logs ADD CONSTRAINT whatsapp_logs_pkey PRIMARY KEY (id);

CREATE INDEX idx_assignment_logs_request ON public.assignment_logs (request_id);
CREATE INDEX idx_conversations_plumber ON public.conversations (plumber_id, last_message_at DESC);
CREATE INDEX idx_conversations_token ON public.conversations (client_access_token);
CREATE INDEX idx_credit_transactions_created ON public.credit_transactions (created_at DESC);
CREATE INDEX idx_credit_transactions_plumber ON public.credit_transactions (plumber_id);
CREATE INDEX idx_italian_cities_cap ON public.italian_cities USING gin (cap);
CREATE INDEX idx_italian_cities_name ON public.italian_cities USING gin (to_tsvector('italian'::regconfig, name));
CREATE INDEX idx_italian_cities_name_lower ON public.italian_cities (lower(name));
CREATE INDEX idx_italian_cities_province ON public.italian_cities (province_code);
CREATE INDEX idx_messages_conv ON public.conversation_messages (conversation_id, created_at);
CREATE INDEX idx_plumber_credits_plumber ON public.plumber_credits (plumber_id);
CREATE INDEX idx_plumber_profiles_areas ON public.plumber_profiles USING gin (service_areas);
CREATE INDEX idx_service_requests_client_user_id ON public.service_requests (client_user_id);
CREATE INDEX idx_service_requests_expires ON public.service_requests (assignment_expires_at) WHERE (status = 'assigned'::text);
CREATE INDEX idx_service_requests_public_meta_city ON public.service_requests_public_meta (city);
CREATE INDEX idx_service_requests_public_meta_created_at ON public.service_requests_public_meta (created_at DESC);
CREATE INDEX idx_service_requests_public_meta_status ON public.service_requests_public_meta (status);
CREATE INDEX idx_service_requests_status ON public.service_requests (status);
CREATE INDEX idx_unregistered_plumbers_active ON public.unregistered_plumbers (is_active) WHERE (is_active = true);
CREATE INDEX idx_unregistered_plumbers_city ON public.unregistered_plumbers (city);
CREATE INDEX idx_whatsapp_logs_created_at ON public.whatsapp_logs (created_at DESC);
CREATE INDEX idx_whatsapp_logs_plumber_id ON public.whatsapp_logs (plumber_id);
CREATE INDEX idx_whatsapp_logs_request_id ON public.whatsapp_logs (request_id);
CREATE INDEX idx_whatsapp_logs_respond_io_message_id ON public.whatsapp_logs (respond_io_message_id) WHERE (respond_io_message_id IS NOT NULL);

ALTER TABLE public.assignment_logs ADD CONSTRAINT assignment_logs_plumber_id_fkey FOREIGN KEY (plumber_id) REFERENCES public.plumber_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.assignment_logs ADD CONSTRAINT assignment_logs_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.service_requests(id) ON DELETE CASCADE;
ALTER TABLE public.contact_logs ADD CONSTRAINT contact_logs_plumber_id_fkey FOREIGN KEY (plumber_id) REFERENCES public.plumber_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.contact_logs ADD CONSTRAINT contact_logs_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.service_requests(id) ON DELETE CASCADE;
ALTER TABLE public.contact_unlocks ADD CONSTRAINT contact_unlocks_plumber_id_fkey FOREIGN KEY (plumber_id) REFERENCES public.plumber_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.contact_unlocks ADD CONSTRAINT contact_unlocks_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.service_requests(id) ON DELETE CASCADE;
ALTER TABLE public.conversation_messages ADD CONSTRAINT conversation_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id) ON DELETE CASCADE;
ALTER TABLE public.conversations ADD CONSTRAINT conversations_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.service_requests(id) ON DELETE CASCADE;
ALTER TABLE public.conversations ADD CONSTRAINT conversations_plumber_id_fkey FOREIGN KEY (plumber_id) REFERENCES public.plumber_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.credit_transactions ADD CONSTRAINT credit_transactions_package_id_fkey FOREIGN KEY (package_id) REFERENCES public.credit_packages(id);
ALTER TABLE public.credit_transactions ADD CONSTRAINT credit_transactions_plumber_id_fkey FOREIGN KEY (plumber_id) REFERENCES public.plumber_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.credit_transactions ADD CONSTRAINT credit_transactions_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.service_requests(id);
ALTER TABLE public.plumber_credits ADD CONSTRAINT plumber_credits_plumber_id_fkey FOREIGN KEY (plumber_id) REFERENCES public.plumber_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.plumber_subscriptions ADD CONSTRAINT plumber_subscriptions_plumber_id_fkey FOREIGN KEY (plumber_id) REFERENCES public.plumber_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.service_requests ADD CONSTRAINT service_requests_accepted_by_id_fkey FOREIGN KEY (accepted_by_id) REFERENCES public.plumber_profiles(id);
ALTER TABLE public.service_requests ADD CONSTRAINT service_requests_assigned_plumber_id_fkey FOREIGN KEY (assigned_plumber_id) REFERENCES public.plumber_profiles(id);
ALTER TABLE public.service_requests_public_meta ADD CONSTRAINT service_requests_public_meta_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.service_requests(id) ON DELETE CASCADE;
ALTER TABLE public.whatsapp_logs ADD CONSTRAINT whatsapp_logs_plumber_id_fkey FOREIGN KEY (plumber_id) REFERENCES public.plumber_profiles(id) ON DELETE SET NULL;
ALTER TABLE public.whatsapp_logs ADD CONSTRAINT whatsapp_logs_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.service_requests(id) ON DELETE SET NULL;

CREATE TRIGGER normalize_city_trigger BEFORE INSERT OR UPDATE OF city ON public.service_requests FOR EACH ROW EXECUTE FUNCTION public.normalize_service_request_city();
CREATE TRIGGER normalize_service_areas_trigger BEFORE INSERT OR UPDATE OF service_areas, main_city ON public.plumber_profiles FOR EACH ROW EXECUTE FUNCTION public.normalize_plumber_service_areas();
CREATE TRIGGER on_plumber_profile_created AFTER INSERT ON public.plumber_profiles FOR EACH ROW EXECUTE FUNCTION public.handle_new_plumber_subscription();
CREATE TRIGGER on_plumber_profile_created_credits AFTER INSERT ON public.plumber_profiles FOR EACH ROW EXECUTE FUNCTION public.handle_new_plumber_credits();
CREATE TRIGGER on_plumber_profile_created_role AFTER INSERT ON public.plumber_profiles FOR EACH ROW EXECUTE FUNCTION public.handle_new_plumber_profile();
CREATE TRIGGER trg_bump_last_message AFTER INSERT ON public.conversation_messages FOR EACH ROW EXECUTE FUNCTION public.bump_conversation_last_message();
CREATE TRIGGER trg_conversations_updated BEFORE UPDATE ON public.conversations FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER trg_create_conversation_on_unlock AFTER INSERT ON public.contact_unlocks FOR EACH ROW EXECUTE FUNCTION public.create_conversation_on_unlock();
CREATE TRIGGER trg_sync_service_requests_public_meta_del AFTER DELETE ON public.service_requests FOR EACH ROW EXECUTE FUNCTION public.sync_service_requests_public_meta();
CREATE TRIGGER trg_sync_service_requests_public_meta_insupd AFTER INSERT OR UPDATE OF city, intervention_type, urgency, property_type, accessibility, status, is_exclusive, created_at ON public.service_requests FOR EACH ROW EXECUTE FUNCTION public.sync_service_requests_public_meta();
CREATE TRIGGER trg_validate_plumber_profile BEFORE INSERT OR UPDATE ON public.plumber_profiles FOR EACH ROW EXECUTE FUNCTION public.validate_plumber_profile();
CREATE TRIGGER update_plumber_profiles_updated_at BEFORE UPDATE ON public.plumber_profiles FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_plumber_subscriptions_updated_at BEFORE UPDATE ON public.plumber_subscriptions FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_service_requests_updated_at BEFORE UPDATE ON public.service_requests FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_subscription_plans_updated_at BEFORE UPDATE ON public.subscription_plans FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_unregistered_plumbers_updated_at BEFORE UPDATE ON public.unregistered_plumbers FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

GRANT SELECT, INSERT, UPDATE, DELETE ON public.assignment_config, public.assignment_logs, public.contact_logs, public.contact_unlocks, public.conversation_messages, public.conversations, public.credit_packages, public.credit_transactions, public.intervention_pricing, public.italian_cities, public.plumber_credits, public.plumber_profiles, public.plumber_subscriptions, public.service_requests, public.service_requests_public_meta, public.subscription_plans, public.unlock_costs, public.unregistered_plumbers, public.whatsapp_logs TO anon, authenticated;
GRANT ALL ON public.assignment_config, public.assignment_logs, public.contact_logs, public.contact_unlocks, public.conversation_messages, public.conversations, public.credit_packages, public.credit_transactions, public.intervention_pricing, public.italian_cities, public.plumber_credits, public.plumber_profiles, public.plumber_subscriptions, public.service_requests, public.service_requests_public_meta, public.subscription_plans, public.unlock_costs, public.unregistered_plumbers, public.whatsapp_logs TO service_role;

ALTER TABLE public.assignment_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assignment_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_unlocks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversation_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.credit_packages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.credit_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.intervention_pricing ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.italian_cities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.plumber_credits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.plumber_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.plumber_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.service_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.service_requests_public_meta ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscription_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.unlock_costs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.unregistered_plumbers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.whatsapp_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins can delete profiles" ON public.plumber_profiles FOR DELETE TO authenticated USING (public.has_role(auth.uid(), 'admin'::public.app_role));
CREATE POLICY "Admins can manage all assignment logs" ON public.assignment_logs USING (public.has_role(auth.uid(), 'admin'::public.app_role));
CREATE POLICY "Admins can manage all contact unlocks" ON public.contact_unlocks USING (public.has_role(auth.uid(), 'admin'::public.app_role));
CREATE POLICY "Admins can manage all credits" ON public.plumber_credits USING (public.has_role(auth.uid(), 'admin'::public.app_role));
CREATE POLICY "Admins can manage all requests" ON public.service_requests TO authenticated USING (public.has_role(auth.uid(), 'admin'::public.app_role)) WITH CHECK (public.has_role(auth.uid(), 'admin'::public.app_role));
CREATE POLICY "Admins can manage all subscriptions" ON public.plumber_subscriptions USING (public.has_role(auth.uid(), 'admin'::public.app_role));
CREATE POLICY "Admins can manage all transactions" ON public.credit_transactions USING (public.has_role(auth.uid(), 'admin'::public.app_role));
CREATE POLICY "Admins can manage assignment config" ON public.assignment_config USING (public.has_role(auth.uid(), 'admin'::public.app_role));
CREATE POLICY "Admins can manage credit packages" ON public.credit_packages USING (public.has_role(auth.uid(), 'admin'::public.app_role));
CREATE POLICY "Admins can manage public request meta" ON public.service_requests_public_meta USING (public.has_role(auth.uid(), 'admin'::public.app_role)) WITH CHECK (public.has_role(auth.uid(), 'admin'::public.app_role));
CREATE POLICY "Admins can manage subscription plans" ON public.subscription_plans USING (public.has_role(auth.uid(), 'admin'::public.app_role));
CREATE POLICY "Admins can manage unlock costs" ON public.unlock_costs USING (public.has_role(auth.uid(), 'admin'::public.app_role));
CREATE POLICY "Admins can manage unregistered plumbers" ON public.unregistered_plumbers USING (public.has_role(auth.uid(), 'admin'::public.app_role));
CREATE POLICY "Admins can update all profiles" ON public.plumber_profiles FOR UPDATE TO authenticated USING (public.has_role(auth.uid(), 'admin'::public.app_role));
CREATE POLICY "Admins can view all contacts" ON public.contact_logs FOR SELECT TO authenticated USING (public.has_role(auth.uid(), 'admin'::public.app_role));
CREATE POLICY "Admins can view all profiles" ON public.plumber_profiles FOR SELECT TO authenticated USING (public.has_role(auth.uid(), 'admin'::public.app_role));
CREATE POLICY "Admins can view all whatsapp logs" ON public.whatsapp_logs FOR SELECT USING (public.has_role(auth.uid(), 'admin'::public.app_role));
CREATE POLICY "Admins manage all conversations" ON public.conversations USING (public.has_role(auth.uid(), 'admin'::public.app_role)) WITH CHECK (public.has_role(auth.uid(), 'admin'::public.app_role));
CREATE POLICY "Admins manage all messages" ON public.conversation_messages USING (public.has_role(auth.uid(), 'admin'::public.app_role)) WITH CHECK (public.has_role(auth.uid(), 'admin'::public.app_role));
CREATE POLICY "Admins manage intervention pricing" ON public.intervention_pricing USING (public.has_role(auth.uid(), 'admin'::public.app_role)) WITH CHECK (public.has_role(auth.uid(), 'admin'::public.app_role));
CREATE POLICY "Anyone can create service requests" ON public.service_requests FOR INSERT TO anon, authenticated WITH CHECK (privacy_accepted = true);
CREATE POLICY "Anyone can view active credit packages" ON public.credit_packages FOR SELECT USING (is_active = true);
CREATE POLICY "Anyone can view assignment config" ON public.assignment_config FOR SELECT USING (true);
CREATE POLICY "Anyone can view cities" ON public.italian_cities FOR SELECT USING (true);
CREATE POLICY "Anyone can view intervention pricing" ON public.intervention_pricing FOR SELECT USING (true);
CREATE POLICY "Anyone can view subscription plans" ON public.subscription_plans FOR SELECT USING (true);
CREATE POLICY "Anyone can view unlock costs" ON public.unlock_costs FOR SELECT USING (true);
CREATE POLICY "Clients insert messages on own conversations" ON public.conversation_messages FOR INSERT TO authenticated WITH CHECK (sender_type = 'client' AND EXISTS (SELECT 1 FROM public.conversations c JOIN public.service_requests sr ON sr.id = c.request_id WHERE c.id = conversation_messages.conversation_id AND (sr.client_user_id = auth.uid() OR (sr.client_email IS NOT NULL AND lower(sr.client_email) = lower(COALESCE(auth.jwt() ->> 'email', ''))))));
CREATE POLICY "Clients see messages on own conversations" ON public.conversation_messages FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.conversations c JOIN public.service_requests sr ON sr.id = c.request_id WHERE c.id = conversation_messages.conversation_id AND (sr.client_user_id = auth.uid() OR (sr.client_email IS NOT NULL AND lower(sr.client_email) = lower(COALESCE(auth.jwt() ->> 'email', ''))))));
CREATE POLICY "Clients see own conversations" ON public.conversations FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.service_requests sr WHERE sr.id = conversations.request_id AND (sr.client_user_id = auth.uid() OR (sr.client_email IS NOT NULL AND lower(sr.client_email) = lower(COALESCE(auth.jwt() ->> 'email', ''))))));
CREATE POLICY "Clients view own requests" ON public.service_requests FOR SELECT TO authenticated USING (client_user_id = auth.uid());
CREATE POLICY "Clients view requests matching own email" ON public.service_requests FOR SELECT TO authenticated USING (client_email IS NOT NULL AND lower(client_email) = lower(COALESCE(auth.jwt() ->> 'email', '')));
CREATE POLICY "Deny anon select plumber_profiles" ON public.plumber_profiles FOR SELECT TO anon USING (false);
CREATE POLICY "Deny anon select service_requests" ON public.service_requests FOR SELECT TO anon USING (false);
CREATE POLICY "Nobody can delete contact logs" ON public.contact_logs FOR DELETE TO authenticated USING (false);
CREATE POLICY "Nobody can delete contact unlocks" ON public.contact_unlocks FOR DELETE TO authenticated USING (public.has_role(auth.uid(), 'admin'::public.app_role));
CREATE POLICY "Nobody can update contact logs" ON public.contact_logs FOR UPDATE TO authenticated USING (false);
CREATE POLICY "Nobody can update contact unlocks" ON public.contact_unlocks FOR UPDATE TO authenticated USING (public.has_role(auth.uid(), 'admin'::public.app_role));
CREATE POLICY "Plumbers can create own unlocks" ON public.contact_unlocks FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM public.plumber_profiles WHERE plumber_profiles.id = contact_unlocks.plumber_id AND plumber_profiles.user_id = auth.uid()));
CREATE POLICY "Plumbers can insert their own profile" ON public.plumber_profiles FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Plumbers can log their contacts" ON public.contact_logs FOR INSERT TO authenticated WITH CHECK (EXISTS (SELECT 1 FROM public.plumber_profiles WHERE plumber_profiles.id = contact_logs.plumber_id AND plumber_profiles.user_id = auth.uid()));
CREATE POLICY "Plumbers can update their own profile" ON public.plumber_profiles FOR UPDATE TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Plumbers can view own credits" ON public.plumber_credits FOR SELECT USING (EXISTS (SELECT 1 FROM public.plumber_profiles WHERE plumber_profiles.id = plumber_credits.plumber_id AND plumber_profiles.user_id = auth.uid()));
CREATE POLICY "Plumbers can view own subscription" ON public.plumber_subscriptions FOR SELECT USING (EXISTS (SELECT 1 FROM public.plumber_profiles WHERE plumber_profiles.id = plumber_subscriptions.plumber_id AND plumber_profiles.user_id = auth.uid()));
CREATE POLICY "Plumbers can view own transactions" ON public.credit_transactions FOR SELECT USING (EXISTS (SELECT 1 FROM public.plumber_profiles WHERE plumber_profiles.id = credit_transactions.plumber_id AND plumber_profiles.user_id = auth.uid()));
CREATE POLICY "Plumbers can view own unlocks" ON public.contact_unlocks FOR SELECT USING (EXISTS (SELECT 1 FROM public.plumber_profiles WHERE plumber_profiles.id = contact_unlocks.plumber_id AND plumber_profiles.user_id = auth.uid()));
CREATE POLICY "Plumbers can view public request meta" ON public.service_requests_public_meta FOR SELECT USING (public.is_plumber(auth.uid()) OR public.has_role(auth.uid(), 'admin'::public.app_role));
CREATE POLICY "Plumbers can view their assigned requests" ON public.service_requests FOR SELECT TO authenticated USING (assigned_plumber_id IN (SELECT pp.id FROM public.plumber_profiles pp WHERE pp.user_id = auth.uid()) OR accepted_by_id IN (SELECT pp.id FROM public.plumber_profiles pp WHERE pp.user_id = auth.uid()) OR public.has_role(auth.uid(), 'admin'::public.app_role));
CREATE POLICY "Plumbers can view their contacts" ON public.contact_logs FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.plumber_profiles WHERE plumber_profiles.id = contact_logs.plumber_id AND plumber_profiles.user_id = auth.uid()));
CREATE POLICY "Plumbers can view their own assignment logs" ON public.assignment_logs FOR SELECT USING (EXISTS (SELECT 1 FROM public.plumber_profiles WHERE plumber_profiles.id = assignment_logs.plumber_id AND plumber_profiles.user_id = auth.uid()));
CREATE POLICY "Plumbers can view their own profile" ON public.plumber_profiles FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Plumbers insert own messages" ON public.conversation_messages FOR INSERT WITH CHECK (sender_type = 'plumber' AND EXISTS (SELECT 1 FROM public.conversations c JOIN public.plumber_profiles pp ON pp.id = c.plumber_id WHERE c.id = conversation_messages.conversation_id AND pp.user_id = auth.uid()));
CREATE POLICY "Plumbers see own conversations" ON public.conversations FOR SELECT USING (EXISTS (SELECT 1 FROM public.plumber_profiles pp WHERE pp.id = conversations.plumber_id AND pp.user_id = auth.uid()));
CREATE POLICY "Plumbers see own messages" ON public.conversation_messages FOR SELECT USING (EXISTS (SELECT 1 FROM public.conversations c JOIN public.plumber_profiles pp ON pp.id = c.plumber_id WHERE c.id = conversation_messages.conversation_id AND pp.user_id = auth.uid()));
CREATE POLICY "Plumbers update own conversations" ON public.conversations FOR UPDATE USING (EXISTS (SELECT 1 FROM public.plumber_profiles pp WHERE pp.id = conversations.plumber_id AND pp.user_id = auth.uid()));

ALTER PUBLICATION supabase_realtime ADD TABLE public.conversations;
ALTER PUBLICATION supabase_realtime ADD TABLE public.conversation_messages;